### ISSUE TITLE
errors: there are a number of build errors during CI

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/generator-theia-extension#164] opened 2023-03-24 17:17 UTC
**Description**

There are a number of build errors during CI which will need to be addressed: 
- https://github.com/eclipse-theia/generator-theia-extension/actions/runs/4513557994/jobs/7948550946

Example:

```
Error: lerna ERR! src/browser/hello-world-contribution.ts(14,10): error TS1239: Unable to resolve signature of parameter decorator when called as an expression.
```

```
Error: lerna ERR! src/browser/example-file/example-file-command.ts(21,10): error TS1239: Unable to resolve signature of parameter decorator when called as an expression.
```

```
Error: src/browser/example-file/example-file-command.ts(21,10): error TS1239: Unable to resolve signature of parameter decorator when called as an expression.
```

**Comment by Shermonbin** [comment] 2023-03-28 06:35
I think this issue is caused by latest TypeScript version5.0.2，When I downgrade the TypeScript version, there are no errors

**Comment by JonasHelming** [comment] 2023-03-28 09:59
Yes, I can confirm, it seems like this issue: https://github.com/microsoft/TypeScript/issues/52435
The original issue would be fixed by an update of inversify. For a quickfix, I suggest to pin the TypeScript version in the generators to the same as used in Theia, does this work for you @vince-fugnitto

**Closed** 2023-03-29 12:08 UTC
